### ISSUE TITLE
Scala 2.12 compatible release

### ISSUE THREAD

**Issue by agarbutt** [kamon-io/kamon-scala#4]
I have a few suggestions for this library that I think might bring clarity / specificity to the libraries they extend.

We could release this library AS-IS versioned as 0.6.5 with support for Scala 2.10, 2.11, and 2.12.
- or -
We could break this library up further into multiple modules; One for each of the `Future` types supported, Scala, Scalaz, and Twitter.

I think there is benefit in the first in, that it will get a 0.6.5 release with Scala 2.12 support available (possibly sooner).  However, the second allows developers to "plugin" the Futures support they want to leverage.  I can see some longer term benefits that come as (if) a Scala Futures implementation falls out of favor.

Thoughts?

**Comment by dpsoft** [comment]
I think that could by a good idea break it in multiple modules but always in this repository or in a new. @ivantopo what do you think?

**Comment by dpsoft** [comment]
@agarbutt I've just released the version 0.6.5.

**Comment by cory-p-oncota** [comment]
@agarbutt I'm greatly in favor of an enhancement that modularizes this library even further. An additional use case are the side-effecting monads from the cats/scalaz world that would benefit from the same kind of tracing we use for futures (e.g. currently working through this with [doobie](https://github.com/tpolecat/doobie) which uses Kleisli composition for its database IO).

**Comment by agarbutt** [comment]
Created PR #5. Looking for feedback.

**Comment by ivantopo** [comment]
I agree with the proposal of breaking it up into different modules, but as @dpsoft said, keep it all in a single repository. I think the repository itself should be called something like "kamon-futures" and then inside we could have these smaller projects for Scala/Twitter/Scalaz and possible Guava/Java later. As long as something is a Future, we can have it in that repo.

That being said, I wouldn't break it up (because of the module name changes) until we release a new major version. We have been talking about some improvements that will land on 0.7.0 so I'l wait until that version to split this thing up, wdyt?

**Comment by agarbutt** [comment]
Sounds reasonable. I'll update the PR with the suggested names.  The PR seems to be in the right direction pending any breaking changes introduced with a 0.7.x release series.

**Comment by dpsoft** [comment]
@agarbutt I've created a new repository called [kamon-futures] in order to follow the @ivantopo idea. you can do a PR there? WDYT?

[kamon-futures]: https://github.com/kamon-io/kamon-futures

**Comment by agarbutt** [comment]
@dpsoft I will move the multi-module changes to the kamon-futures repository later today.

**Comment by agarbutt** [comment]
PR #6 submitted for review to support Scala 2.10, 2.11, and 2.12 with the library structured as-is.
